Vagrant.configure("2") do |config|
    config.hostmanager.enable = true
    config.hostmanager.manage_host = true

## DB vm ###
    config.vm.define "db01" do |db01|
        db01.vm.box = "geerlingguy/centos7"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.33.15"
        db01.vm.provision "shell", path: "mysql.sh"
    end


## Memcache vm ##
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "geerlingguy/centos7"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.33.14"
        mc01.vm.provision "shell", path: "memcache.sh"
    end


## RabbitMQ vm  ###
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "geerlingguy/centos7"
        rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", ip: "192.168.33.16"
        rmq01.vm.provision "shell", path: "rabbitmq.sh"
    end

